# Generated by Django 2.1.4 on 2020-03-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
    ]
